//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace netCollections {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("netCollections.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The argument may not be less than zero..
        /// </summary>
        internal static string ArgMustNotBeNegative {
            get {
                return ResourceManager.GetString("ArgMustNotBeNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The array is too small to hold all of the items..
        /// </summary>
        internal static string ArrayTooSmall {
            get {
                return ResourceManager.GetString("ArrayTooSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Comparand is not of the correct type..
        /// </summary>
        internal static string BadComparandType {
            get {
                return ResourceManager.GetString("BadComparandType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The \&quot;{0}\&quot; collection is read-only and cannot be modified..
        /// </summary>
        internal static string CannotModifyCollection {
            get {
                return ResourceManager.GetString("CannotModifyCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The capacity may not be less than Count..
        /// </summary>
        internal static string CapacityLessThanCount {
            get {
                return ResourceManager.GetString("CapacityLessThanCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Collection was modified during an enumeration..
        /// </summary>
        internal static string ChangeDuringEnumeration {
            get {
                return ResourceManager.GetString("ChangeDuringEnumeration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The collection is empty..
        /// </summary>
        internal static string CollectionIsEmpty {
            get {
                return ResourceManager.GetString("CollectionIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The collection may not be read only..
        /// </summary>
        internal static string CollectionIsReadOnly {
            get {
                return ResourceManager.GetString("CollectionIsReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The collection has become too large..
        /// </summary>
        internal static string CollectionTooLarge {
            get {
                return ResourceManager.GetString("CollectionTooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The Compare method is not supported on an identity comparer..
        /// </summary>
        internal static string IdentityComparerNoCompare {
            get {
                return ResourceManager.GetString("IdentityComparerNoCompare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The two collections cannot be combined because they use different comparison operations..
        /// </summary>
        internal static string InconsistentComparisons {
            get {
                return ResourceManager.GetString("InconsistentComparisons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The load factor must be between 0.25 and 0.95..
        /// </summary>
        internal static string InvalidLoadFactor {
            get {
                return ResourceManager.GetString("InvalidLoadFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The key was already present in the dictionary..
        /// </summary>
        internal static string KeyAlreadyPresent {
            get {
                return ResourceManager.GetString("KeyAlreadyPresent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The key was not found in the collection..
        /// </summary>
        internal static string KeyNotFound {
            get {
                return ResourceManager.GetString("KeyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The list may not be read only..
        /// </summary>
        internal static string ListIsReadOnly {
            get {
                return ResourceManager.GetString("ListIsReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The get accessor of the indexer must be overridden..
        /// </summary>
        internal static string MustOverrideIndexerGet {
            get {
                return ResourceManager.GetString("MustOverrideIndexerGet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The set accessor of the indexer must be overridden..
        /// </summary>
        internal static string MustOverrideIndexerSet {
            get {
                return ResourceManager.GetString("MustOverrideIndexerSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a This method must be overridden or re-implemented in the derived class..
        /// </summary>
        internal static string MustOverrideOrReimplement {
            get {
                return ResourceManager.GetString("MustOverrideOrReimplement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The argument is outside the range of this View..
        /// </summary>
        internal static string OutOfViewRange {
            get {
                return ResourceManager.GetString("OutOfViewRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reset is not supported on this enumerator..
        /// </summary>
        internal static string ResetNotSupported {
            get {
                return ResourceManager.GetString("ResetNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Type \&quot;{0}\&quot; does not implement ICloneable..
        /// </summary>
        internal static string TypeNotCloneable {
            get {
                return ResourceManager.GetString("TypeNotCloneable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Type &quot;{0}&quot; does not implement IComparable&lt;{0}&gt; or IComparable..
        /// </summary>
        internal static string UncomparableType {
            get {
                return ResourceManager.GetString("UncomparableType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The value \&quot;{0}\&quot; isn&apos;t of type \&quot;{1}\&quot; and can&apos;t be used in this generic collection..
        /// </summary>
        internal static string WrongType {
            get {
                return ResourceManager.GetString("WrongType", resourceCulture);
            }
        }
    }
}
